remote_theme: daviddarnes/alembic
plugins:
- jekyll-include-cache
- jekyll-remote-theme
locale: "en-US"
title: "My academic webpage"
name: "Audrey Shingleton"
url: "https://Audreym98.github.io"
search: true
logo: "/assets/as_headshot.jpg"
author:
  name             : "Audrey Shingleton"
  avatar           : "/assets/as_headshot.jpg"
  bio              : "I am a Master's student in Computer Science at the University of Montana"
  location         : "UM"
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

include:
  - _pages
