remote_theme: mmistakes/minimal-mistakes@4.17.2
plugins:
- jekyll-include-cache
locale: "en-US"
title: "My academic webpage"
name: "Audrey Shingleton"
url: "https://Audreym98.github.io"
search: true
logo: "/assets/as_headshot.jpg"
author:
  name             : "Audrey Shingleton"
  avatar           : "/assets/as_headshot.jpg"
  bio              : "I am a Master's student in Computer Science"
  location         : "UM"
